In [4]:
import pandas as pd
import numpy as np

In [5]:
from pandas import Series, DataFrame

# 5.1 Introduction to pandas Data Structures

### Series

A Series is a one-dimensional array-like object containing a sequence of values (of similar types to NumPy types) and an associated array of data labels, called its index. The simplest Series is formed from only an array of data:

In [7]:
# constructing a series
obj = pd.Series([4, 7, -5, 3])

In [8]:
# calling the series object, returns data
obj

0    4
1    7
2   -5
3    3
dtype: int64

And so on...
Note now the default keys for the Series are integer indexed 0 through (N-1)

In [9]:
# .modifiers work on pandas Series, array representation
obj.values
# returns an array object of values within obj

array([ 4,  7, -5,  3])

In [10]:
obj.index
# returns RangeIndex object that contains the range data for the object

RangeIndex(start=0, stop=4, step=1)

In [11]:
# declaring a new object with specific index
obj2 = pd.Series([4, 7, -5, 3], index=['d','b','a','c'])

In [12]:
obj2
# returns obj2, note the dtype explaining the singular data type contained within the series

d    4
b    7
a   -5
c    3
dtype: int64

In [17]:
obj2.index
# returns array type of index of keys based on order, with dtype indentifier

Index(['d', 'b', 'a', 'c'], dtype='object')

In [18]:
obj2['a']
# objects can be called by their 'labels' aka their object indexes 

-5

In [19]:
obj2['d'] = 6
# the data when called can be ovewritten to contain different data

In [20]:
obj2[['c', 'a', 'd']]
# partial calls are also viable, and only return the selected data
# note how the argument is passed in within a list

c    3
a   -5
d    6
dtype: int64

In [21]:
# object call also takes conditional arguments
obj2[obj2 > 0]
# the return is the label(key)-value pairs that the conditional deems true

d    6
b    7
c    3
dtype: int64

In [23]:
# scalar mutators can also be applied to the Series object
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [24]:
# in particular, numPy works very well with Pandas objects
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Another way to think about a Series is as a fixed-length, ordered dict, as it is a map‐ ping of index values to data values. It can be used in many contexts where you might use a dict:

In [25]:
'b' in obj2
# returns conditional if label 'b' is within obj2

True

In [26]:
'e' in obj2

False

Should you have data contained in a Python dict, you can create a Series from it by passing the dict:

In [27]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [28]:
obj3 = pd.Series(sdata)

In [29]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

When you are only passing a dict, the index in the resulting Series will have the dict’s keys in sorted order. You can override this by passing the dict keys in the order you want them to appear in the resulting Series:

In [30]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [31]:
obj4 = pd.Series(sdata, index=states)

In [32]:
obj4
# There values found in 'sdata' were placed in the appropriate locations, but since California has no value,
# California was created as a null entity with all fields containing NaN

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [33]:
# You can use .modifier .isnull() to determine if data contains values, like seen in past examples
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [34]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [35]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [36]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [37]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [38]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [39]:
obj4.name = 'population'

In [40]:
obj4.index.name = 'state'

In [41]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [42]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [43]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [44]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [45]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
       }
frame = pd.DataFrame(data)

In [46]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [47]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [48]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [49]:
frame2 = pd.DataFrame(data, columns=['year','state','pop','debt',''],
                     index=['one','two','three','four','fixe','six']
                     )

In [50]:
frame2

year   state  pop debt     
one    2000    Ohio  1.5  NaN  NaN
two    2001    Ohio  1.7  NaN  NaN
three  2002    Ohio  3.6  NaN  NaN
four   2001  Nevada  2.4  NaN  NaN
fixe   2002  Nevada  2.9  NaN  NaN
six    2003  Nevada  3.2  NaN  NaN

In [51]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', ''], dtype='object')

In [52]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
fixe     Nevada
six      Nevada
Name: state, dtype: object

In [53]:
frame2.year

one      2000
two      2001
three    2002
four     2001
fixe     2002
six      2003
Name: year, dtype: int64

In [54]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
          NaN
Name: three, dtype: object

In [55]:
frame2['debt'] = 16.5

In [56]:
frame2

year   state  pop  debt     
one    2000    Ohio  1.5  16.5  NaN
two    2001    Ohio  1.7  16.5  NaN
three  2002    Ohio  3.6  16.5  NaN
four   2001  Nevada  2.4  16.5  NaN
fixe   2002  Nevada  2.9  16.5  NaN
six    2003  Nevada  3.2  16.5  NaN

In [57]:
frame2['debt'] = np.arange(6.)

In [58]:
frame2

year   state  pop  debt     
one    2000    Ohio  1.5   0.0  NaN
two    2001    Ohio  1.7   1.0  NaN
three  2002    Ohio  3.6   2.0  NaN
four   2001  Nevada  2.4   3.0  NaN
fixe   2002  Nevada  2.9   4.0  NaN
six    2003  Nevada  3.2   5.0  NaN

In [59]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two','four','five'])

In [60]:
frame2['debt'] = val

In [61]:
frame2

year   state  pop  debt     
one    2000    Ohio  1.5   NaN  NaN
two    2001    Ohio  1.7  -1.2  NaN
three  2002    Ohio  3.6   NaN  NaN
four   2001  Nevada  2.4  -1.5  NaN
fixe   2002  Nevada  2.9   NaN  NaN
six    2003  Nevada  3.2   NaN  NaN

In [62]:
frame2['eastern'] = frame2.state == 'Ohio'

In [63]:
frame2

year   state  pop  debt       eastern
one    2000    Ohio  1.5   NaN  NaN     True
two    2001    Ohio  1.7  -1.2  NaN     True
three  2002    Ohio  3.6   NaN  NaN     True
four   2001  Nevada  2.4  -1.5  NaN    False
fixe   2002  Nevada  2.9   NaN  NaN    False
six    2003  Nevada  3.2   NaN  NaN    False

In [64]:
del frame2['eastern']

In [65]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', ''], dtype='object')

In [66]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [67]:
frame3 = pd.DataFrame(pop)

In [68]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [69]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [70]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [71]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [72]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [73]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [74]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [75]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [76]:
frame2.values

array([[2000, 'Ohio', 1.5, nan, nan],
       [2001, 'Ohio', 1.7, -1.2, nan],
       [2002, 'Ohio', 3.6, nan, nan],
       [2001, 'Nevada', 2.4, -1.5, nan],
       [2002, 'Nevada', 2.9, nan, nan],
       [2003, 'Nevada', 3.2, nan, nan]], dtype=object)

Index Objects

In [77]:
obj = pd.Series(range(3), index=['a','b','c'])

In [78]:
index = obj.index

In [79]:
index

Index(['a', 'b', 'c'], dtype='object')

In [80]:
index[1:]

Index(['b', 'c'], dtype='object')

In [81]:
index[1] # = 'd' # gives type error

'b'

In [82]:
labels = pd.Index(np.arange(3))

In [83]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [84]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [85]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [86]:
obj2.index is labels

True

In [87]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [88]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [89]:
'Ohio' in frame3.columns

True

In [90]:
2003 in frame3.index

False

In [91]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [92]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

Reindexing

In [93]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d','b','a','c'])

In [94]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [95]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [96]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [97]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [98]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [99]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [100]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a','c','d'],
                     columns=['Ohio','Texas','California'])

In [109]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [110]:
frame2 = frame.reindex(['a','b','c','d'])

In [111]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [104]:
states = ['Texas', 'Utah', 'California']

In [107]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [113]:
frame1.loc[['a', 'b', 'c', 'd'], states]
# this gives an error because 'Utah is not within index'

KeyError: "['Utah'] not in index"

### Dropping Entries From an Axis

In [115]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [117]:
new_obj = obj.drop('c')

In [119]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [121]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [124]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio','Colorado','Utah','New York'],
                   columns=['one','two','three','four']
                   )
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [125]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [128]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [129]:
data.drop(['two','four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [130]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [131]:
obj['b']

1.0

In [132]:
obj[1]

1.0

In [133]:
obj[2:4]

d    3.0
e    4.0
dtype: float64

In [135]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [136]:
obj[[1, 3]]

b    1.0
e    4.0
dtype: float64

In [137]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [138]:
obj['b':'c']

b    1.0
dtype: float64

In [140]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
d    3.0
e    4.0
dtype: float64

In [144]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [145]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [147]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [148]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [149]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [150]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [152]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [153]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [154]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [155]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [156]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [157]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [159]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [164]:
ser = pd.Series(np.arange(3.))
ser
# ser[-1] # gives fallback error (buggy)

0    0.0
1    1.0
2    2.0
dtype: float64

In [169]:
ser2 = pd.Series(np.arange(3.), index=['a','b','c'])
ser2[-1]

2.0

In [170]:
ser[:1]

0    0.0
dtype: float64

In [171]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [172]:
ser.iloc[:1]

0    0.0
dtype: float64

In [173]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a','c','d','e'])

In [174]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
              index=['a','c','e','f','g'])

In [175]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [176]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [177]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [178]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                  index=['Ohio','Texas','Colorado'])

In [179]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio','Texas', 'Oregon'])

In [180]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [181]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [182]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [183]:
df1 = pd.DataFrame({'A': [1, 2]})

In [184]:
df2 = pd.DataFrame({'B': [3, 4]})

In [185]:
df1

A
0  1
1  2

In [186]:
df2

B
0  3
1  4

In [187]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [188]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))

In [190]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns=list('abcde'))

In [191]:
df2.loc[1, 'b'] = np.nan

In [192]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [193]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [194]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [195]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [196]:
1 / df1 

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [197]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [198]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [199]:
arr = np.arange(12.).reshape((3, 4))
arr

In [201]:
arr[0]

array([0., 1., 2., 3.])

In [202]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [203]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [204]:
series = frame.iloc[0]

In [205]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [206]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [207]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [208]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [209]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [211]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [212]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [213]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [214]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [215]:
frame

b         d         e
Utah    0.261975 -0.042152  2.309391
Ohio   -0.474913  0.811255 -0.545617
Texas   1.538852 -1.244944  0.427397
Oregon -0.553057 -0.301750  0.247149

In [216]:
np.abs(frame)

b         d         e
Utah    0.261975  0.042152  2.309391
Ohio    0.474913  0.811255  0.545617
Texas   1.538852  1.244944  0.427397
Oregon  0.553057  0.301750  0.247149

In [217]:
f = lambda x: x.max() - x.min()

In [218]:
frame.apply(f)

b    2.091909
d    2.056199
e    2.855009
dtype: float64

In [219]:
frame.apply(f, axis='columns')

Utah      2.351543
Ohio      1.356873
Texas     2.783796
Oregon    0.800206
dtype: float64

In [221]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [222]:
frame.apply(f)

b         d         e
min -0.553057 -1.244944 -0.545617
max  1.538852  0.811255  2.309391

In [223]:
format = lambda x: '%.2f' % x

In [224]:
frame.applymap(format)

b      d      e
Utah     0.26  -0.04   2.31
Ohio    -0.47   0.81  -0.55
Texas    1.54  -1.24   0.43
Oregon  -0.55  -0.30   0.25

In [225]:
frame['e'].map(format)

Utah       2.31
Ohio      -0.55
Texas      0.43
Oregon     0.25
Name: e, dtype: object

In [226]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [227]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [228]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=['three', 'one'],
                    columns=['d','a','b','c'])

In [229]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [230]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [231]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [232]:
obj = pd.Series([4, 7, -3, 2])

In [233]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [234]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [235]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [237]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 
                     'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [238]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [239]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [240]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [241]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [242]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [243]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [244]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2],
                     'a': [0, 1, 0, 1],
                     'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [245]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [247]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [248]:
obj.index.is_unique

False

In [249]:
obj['a']

a    0
a    1
dtype: int64

In [250]:
obj['c']

4

In [252]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a -0.530392 -0.826054 -1.173355
a -0.312975  1.505331 -2.677270
b  0.344166 -0.532021 -0.038990
b  0.778608 -1.328335 -1.873365

In [253]:
df.loc['b']

0         1         2
b  0.344166 -0.532021 -0.038990
b  0.778608 -1.328335 -1.873365

In [255]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                 index=['a','b','c','d'],
                 columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [256]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [257]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [258]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [259]:
df.idxmax()

one    b
two    d
dtype: object

In [260]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [261]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [262]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [263]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

Correlation and Covariance

In [265]:
import sys
!{sys.executable} -m pip install pandas-datareader

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.5/109.5 kB 1.7 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 24.7 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
  Created wheel for lxml: filename=lxml-4.9.1-cp310-cp310-macosx_12_0_arm64.whl size=1492433 sha256=4a7a3d24dc987d1478334332e0c44e9e6f65eec5ea985e065fb9ee2856efec27
  Stored in directory: /Users/jj/Library/Caches/pip/wheels/a4/ec/7b/8acde6da24b5aabeee049213d5bec12d1e9214d3cae276387b
Successfully built lxml

[notice] A new release of pip available: 22.1.2 -> 22.2
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/3.4.3/libexec/bin/python3.10 -m pip install --upgrade pip


In [266]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [267]:
returns = price.pct_change()

In [268]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2022-07-21  0.015094 -0.015714  0.009799  0.002964
2022-07-22 -0.008111  0.008651 -0.016916 -0.058067
2022-07-25 -0.007398  0.002261 -0.005876 -0.001384
2022-07-26 -0.008826 -0.003579 -0.026774 -0.025598
2022-07-27  0.015908  0.001562  0.047340  0.065914

In [269]:
returns['MSFT'].corr(returns['IBM'])

0.4767028994699897

In [270]:
returns['MSFT'].cov(returns['IBM'])

0.00015217812152947734

In [271]:
returns.MSFT.corr(returns.IBM)

0.4767028994699897

In [272]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.432526  0.756345  0.681161
IBM   0.432526  1.000000  0.476703  0.442840
MSFT  0.756345  0.476703  1.000000  0.785806
GOOG  0.681161  0.442840  0.785806  1.000000

In [273]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000410  0.000150  0.000285  0.000257
IBM   0.000150  0.000294  0.000152  0.000142
MSFT  0.000285  0.000152  0.000347  0.000273
GOOG  0.000257  0.000142  0.000273  0.000348

In [275]:
returns.corrwith(returns.IBM)

AAPL    0.432526
IBM     1.000000
MSFT    0.476703
GOOG    0.442840
dtype: float64

In [276]:
returns.corrwith(volume)

AAPL   -0.076385
IBM    -0.113895
MSFT   -0.074912
GOOG   -0.087499
dtype: float64

In [277]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [279]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [280]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [281]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [282]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [284]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [285]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [286]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [287]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [288]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [290]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                    'Qu2': [2, 3, 1, 2, 3],
                    'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [291]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [292]:
# end of chapter